---
version: 1

dependencies:
 galaxy: requirements.yml
 python: requirements.txt
 system: bindep.txt

additional_build_steps:
 append:
    - RUN wget https://get.helm.sh/helm-v3.7.1-linux-amd64.tar.gz -O - | tar -xz && mv linux-amd64/helm /usr/bin/helm && chmod +x /usr/bin/helm && rm -rf linux-amd64
