
name: Testing Container
on: [push]
jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
